package:
  name: eccc_rpnpy
  version: 2.2.0rc3

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - pytz
    - numpy >1.22

  run:
    - python
    - pytz
    - numpy >1.22
    - scipy
    - eccc_librmn >=20.0.3
    - eccc_libezinterpv >=20.0.1
    - eccc_libtdpack >=1.6.3
    - eccc_libvgrid >=6.9.3
    - eccc_libburpc >=1.17

test:
  imports:
    - rpnpy.librmn.all
    - rpnpy.vgd.all
    - rpnpy.utils.fstd3d
    - rpnpy.rpndate
    - rpnpy.burpc.all
    - rpnpy.tdpack.all

about:
  home: https://github.com/sebastiendfortier/python-rpn
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'MSC python rpn library'

source:
  path: ../python-rpn
  
