package:
  name: spookipy
  version: 2024.01.00

build:
  number: 1

requirements:
  build:
    - python
    - pandas >=1.2.4
    - numpy >=1.19.5
    - dask >=2021.8.0
    - xarray
    - fstpy >=2023.11.00

  run:
    - python
    - pandas >=1.2.4
    - numpy >=1.19.5
    - dask >=2021.8.0
    - xarray
    - eccc_rpnpy >=2.2.0rc3
    - fstpy >=2023.11.00

test:
  imports:
    - spookipy

about:
  home: https://github.com/sebastiendfortier/spookipy
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'MSC collection of python algorithms that work with dataframes obtained with fstpy or numpy arrays.'

source:
  path: ../spookipy

