package:
  name: fstpy
  version: 2023.11.00

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - pandas >=1.2.4
    - numpy >=1.19.5
    - dask >=2021.8.0

  run:
    - python
    - pandas >=1.2.4
    - numpy >=1.19.5
    - dask >=2021.8.0
    - eccc_rpnpy >=2.2.0rc3

test:
  imports:
    - fstpy

about:
  home: https://github.com/sebastiendfortier/fstpy
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'MSC Pandas/dask interface for RPN standard files (from Environment Canada).'

source:
  path: ../fstpy

