package:
  name: ci_fstcomp
  version: 1.0.8

build:
  number: 0
  noarch: python
  
requirements:
  build:
    - python
    - numpy >=1.19.5

  run:
    - python 
    - numpy >=1.19.5
    - pandas >=1.2.4
    - eccc_rpnpy >=2.2.0rc3

test:
  imports:
    - ci_fstcomp

about:
  home: https://github.com/sebastiendfortier/ci_fstcomp
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'MSC fstcomp library for python an ci client for comparing fst files'

source:
  path: ../ci_fstcomp

 