package:
  name: jupyter-rsession-proxy
  version: 2.2.1

build:
  number: 1
  noarch: python

requirements:
  build:
    - python
    - jupyter-server-proxy>=3.2.3,!=4.0.0,!=4.1.0

  run:
    - python
    - jupyter-server-proxy>=3.2.3,!=4.0.0,!=4.1.0

about:
  home: https://github.com/sebastiendfortier/jupyter-rsession-proxy
  license: BSD clause 3
  license_family: BSD
  license_file: LICENSE
  summary: 'jupyter-rsession-proxy provides Jupyter server and notebook extensions to proxy RStudio.'

source:
  path: ../jupyter-rsession-proxy

