package:
  name: eccc_support_libs
  version: 2023.12.0


about:
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'CMC support libraries'
  build_environment:
    - linux-64
    - glibc=2.23

source:
  path: ../../support_libraries
