package:
  name: cmcdict
  version: 2024.07.22

build:
  number: 0
  noarch: python
  
requirements: 
  build:
    - python

  run:
    - python


test:
  imports:
    - cmcdict

about:
  home: https://github.com/sebastiendfortier/cmcdict
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'MSC python library to work with the CMC operational dictionary'

source:
  path: ../cmcdict
 